<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/dashboard/index">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/blog">
              <span data-feather="file"></span>
              Blogs
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/dashboard/addblog">
              <span data-feather="file"></span>
              Add Blog
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/dashboard/bloglist">
              <span data-feather="shopping-cart"></span>
              Blog List
            </a>
          </li>
          <li class="nav-item" style='display:<?php if($_SESSION['mydetails']['role'] == 'admin') echo "block"; else echo "none";?>'>
            <a class="nav-link" href="/dashboard/readers">
              <span data-feather="users"></span>
              Readers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li>
        </ul>        
      </div>
    </nav>